[dependencies]
base = "0.9.7"
certified-cache = "0.2.0"
json = "https://github.com/aviate-labs/json.mo#main"
array = "https://github.com/aviate-labs/array.mo#main"
encoding = "https://github.com/aviate-labs/encoding.mo#main"
motoko-sha = "https://github.com/enzoh/motoko-sha#master"
hashmap = "https://github.com/ZhenyaUsenko/motoko-hash-map#master"
serde = "0.2.0"
test = "1.0.1"
assets = "0.2.0"
"http-parser.mo" = "https://github.com/NatLabs/http-parser.mo#v0.1.2"
server = "0.2.2"